version: '3.7'

services:
  db:
    image: postgres
    container_name: rentalx_db
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=rentalx
      - POSTGRES_PASSWORD=rentalx
      - POSTGRES_DB=rentalx
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: rentalx_app
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    links:
      - db
    depends_on:
      - db

volumes:
  pgdata:
